m

diff --git a/bin/hodt2doc b/bin/hodt2doc
--- a/bin/hodt2doc
+++ b/bin/hodt2doc
@@ -1,39 +1,20 @@
 #!/bin/sh -e
-#L:  MIT License
-#L:
-#l:  Copyright (c) 2023 Harkaitz Agirre, harkaitz.aguirre@gmail.com
-#L:
-#L:  Permission is hereby granted, free of charge, to any person obtaining a copy
-#L:  of this software and associated documentation files (the "Software"), to deal
-#L:  in the Software without restriction, including without limitation the rights
-#L:  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-#L:  copies of the Software, and to permit persons to whom the Software is
-#L:  furnished to do so, subject to the following conditions:
-#L:
-#L:  The above copyright notice and this permission notice shall be included in all
-#L:  copies or substantial portions of the Software.
-#L:
-#L:  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-#L:  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-#L:  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-#L:  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-#L:  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-#L:  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
-#L:  SOFTWARE.
-#h: Usage: $0 ODT DOC
+##:
+#h: Usage: hodt2doc ODT DOC
 #h:
 #h: Transform an Open Office ODT file to DOC using `soffice command.
+##:
 hodt2doc() {
     local odt="$1" doc="$2"
     if test ! -n "${odt}";then
-        echo "${SCRNAME}: error: Please specify an odt file." >&2
+        echo "error: Please specify an odt file." >&2
         return 1
     elif test ! -f "${odt}";then
-        echo "${SCRNAME}: error: File ${odt} does not exist." >&2
+        echo "error: File ${odt} does not exist." >&2
         return 1
     fi
     if test ! -n "${doc}";then
-        echo "${SCRNAME}: error: Please specify a doc file." >&2
+        echo "error: Please specify a doc file." >&2
         return 1
     fi
     if test -d "${doc}";then
@@ -43,28 +24,19 @@ hodt2doc() {
     fi
     mkdir -p "${dir}"
     local tfile="${dir}"/"`basename ${odt} .odt`.doc"
-    hodt2doc_vrun            \
-        soffice              \
-        --headless           \
-        --convert-to doc     \
-        --outdir "${dir}"    \
+    soffice               \
+        --headless        \
+        --convert-to doc  \
+        --outdir "${dir}" \
         "${odt}"
     sleep 1
     if test ! -d "${doc}";then
-        hodt2doc_vrun mv "${tfile}" "${doc}"
+        mv "${tfile}" "${doc}"
     fi
 }
-hodt2doc_vrun() {
-    echo "${SCRNAME}: $*" >&2
-    "$@"
-}
-SCRNAME="`basename "$0"`"
-if test @"${SCRNAME}" = @"hodt2doc";then
-    if test -n "$1";then
-        hodt2doc "$@"
-    else
-        sed -n 's/^ *#h: \{0,1\}//p' "$0" | sed "s|\\\$0|`basename $0`|g"
-        echo ""
-        sed -n 's/^ *#l: \{0,2\}//p' "$0"
-    fi
+if test @"$(basename "$0")" = @"hodt2doc"; then
+    case "${1}" in
+        ''|-h|--help) sed -n 's/^ *#h: \{0,1\}//p' "$0" ;;
+        *)            hodt2doc "$@"; exit 0;;
+    esac
 fi
diff --git a/bin/hodt2html b/bin/hodt2html
--- a/bin/hodt2html
+++ b/bin/hodt2html
@@ -1,46 +1,25 @@
 #!/bin/sh -e
-#L:  MIT License
-#L:
-#l:  Copyright (c) 2023 Harkaitz Agirre, harkaitz.aguirre@gmail.com
-#L:
-#L:  Permission is hereby granted, free of charge, to any person obtaining a copy
-#L:  of this software and associated documentation files (the "Software"), to deal
-#L:  in the Software without restriction, including without limitation the rights
-#L:  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-#L:  copies of the Software, and to permit persons to whom the Software is
-#L:  furnished to do so, subject to the following conditions:
-#L:
-#L:  The above copyright notice and this permission notice shall be included in all
-#L:  copies or substantial portions of the Software.
-#L:
-#L:  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-#L:  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-#L:  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-#L:  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-#L:  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-#L:  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
-#L:  SOFTWARE.
 ##:
-#h: Usage: $0 ODT DIR
+#h: Usage: hodt2html ODT DIR
 #h:
 #h: Convert ODT files to HTML format.
 ##:
 hodt2html() {
     local odt="$1" dir="$2" fmt="html:HTML (StarWriter):UTF8"
     if test ! -n "${odt}"; then
-        error "Please specify an odt file."
+        echo >&2 "error: Please specify an odt file."
         return 1
     elif test ! -n "${dir}"; then
-        error "Please specify a directory."
+        echo >&2 "error: Please specify a directory."
         return 1
     elif test ! -f "${odt}"; then
-        error "${odt}: The file does not exist."
+        echo >&2 "error: ${odt}: The file does not exist."
         return 1
     elif test ! -d "${dir}"; then
-        error "${dir}: The directory does not exist."
+        echo >&2 "error: ${dir}: The directory does not exist."
         return 1
     elif ! which "soffice" >/dev/null 2>&1; then
-        error "Command 'soffice' not found."
+        echo >&2 "error: Command 'soffice' not found."
         return 1
     fi
     LD_LIBRARY_PATH=/lib64    \
@@ -51,20 +30,10 @@ hodt2html() {
         "${odt}" >/dev/null 2>&1
     sleep 2
 }
-## -----------------------------------------------------------------------------
-
-## -----------------------------------------------------------------------------
-error() { echo "${SCRNAME}: error: $*" >&2; }
-SCRNAME="`basename "$0"`"
-if test @"${SCRNAME}" = @"hodt2html";then
+## -------------------------------------------------------------------
+if test @"$(basename "$0")" = @"hodt2html";then
     case "${1}" in
-        ''|-h|--help)
-            sed -n 's/^ *#h: \{0,1\}//p' "$0" | sed "s|\\\$0|${SCRNAME}|g"
-            echo ""
-            sed -n 's/^ *#l: \{0,2\}//p' "$0"
-            ;;
-        *)
-            hodt2html "$@"
-            ;;
+        ''|-h|--help) sed -n 's/^ *#h: \{0,1\}//p' "$0" ;;
+        *)            hodt2html "$@"; exit 0;;
     esac
 fi
diff --git a/bin/icon-tool b/bin/icon-tool
--- a/bin/icon-tool
+++ b/bin/icon-tool
@@ -1,32 +1,12 @@
 #!/bin/sh -e
-#L:  MIT License
-#L:
-#l:  Copyright (c) 2023 Harkaitz Agirre, harkaitz.aguirre@gmail.com
-#L:
-#L:  Permission is hereby granted, free of charge, to any person obtaining a copy
-#L:  of this software and associated documentation files (the "Software"), to deal
-#L:  in the Software without restriction, including without limitation the rights
-#L:  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-#L:  copies of the Software, and to permit persons to whom the Software is
-#L:  furnished to do so, subject to the following conditions:
-#L:
-#L:  The above copyright notice and this permission notice shall be included in all
-#L:  copies or substantial portions of the Software.
-#L:
-#L:  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-#L:  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-#L:  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-#L:  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-#L:  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-#L:  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
-#L:  SOFTWARE.
 ##:
-#h: Usage: $0 ...
+#h: Usage: icon-tool ...
 #h:
 #h: Icon and logo check and transformation tool.
 #h:
 #h: ... get-size [FILE|SIZE] : Get size, list sizes.
 #h: ... android-app  ...     : Android app operations.
+##:
 icon_tool() {
     local cmd="$1"
     shift
@@ -133,23 +113,11 @@ icon_tool_android_app_play_icon() {
         convert "${f}" -quiet -resize "512x512!" "${t}"
     done
 }
-
-
-
-## ----------------------------------------------
-icon_tool_log()   { echo "${SCRNAME}: $*" >&2; }
-icon_tool_error() { icon_tool_log "error: $*"; }
-## ----------------------------------------------
-SCRNAME="`basename "$0"`"
-if test @"${SCRNAME}" = @"icon-tool";then
+## -------------------------------------------------------------------
+icon_tool_error() { echo >&2 "error: $*"; }
+if test @"$(basename "$0")" = @"icon-tool";then
     case "${1}" in
-        ''|-h|--help)
-            sed -n 's/^ *#h: \{0,1\}//p' "$0" | sed "s|\\\$0|${SCRNAME}|g"
-            echo ""
-            sed -n 's/^ *#l: \{0,2\}//p' "$0"
-            ;;
-        *)
-            icon_tool "$@"
-            ;;
+        ''|-h|--help) sed -n 's/^ *#h: \{0,1\}//p' "$0" ;;
+        *)            icon_tool "$@"; exit 0;;
     esac
 fi
